### ISSUE TITLE
Cannot resize size of keys and layout. 

### ISSUE THREAD

**Issue by smunmun** [wooningeire/plover-touchscreen-stenotype#9]
Currently shows up too large on an 1800x1200 screen. Covers almost the entire screen with some keys offscreen.

**Comment by wooningeire** [comment]
The key size/spacing is dependent on the display DPI (with some logic that keeps the physical size of the keys approximately consistent across different displays), so whether or not it fits on the screen is a matter of the screen's physical measurements rather than the pixel dimensions. I originally had the base key size fixed to 1.8 cm (roughly the size of the keys on the keyboards I measured) but bumped it up to 2 cm later on to reduce misstrokes. Do the middle and ring finger columns appear larger than 2 cm on your screen?

As for changing the size, I'm wondering how we'd want to implement the size customization in the settings dialog:
- Scaling factor?
- Being able to specify the base key width/height, compound key size, etc., in cm, separately?
- Being able to import SVGs for layouts? (maybe further down the line)

**Comment by smunmun** [comment]
It shows up as the right size. I would assume being able to set the size of the keys in cm would help for my small screen, especially since having the keys larger to prevent misstrokes is a preference thing anyway. And being able to import SVGs in the future could be very useful for people who design their own boards and want to try and see if their layout works before they build it! Super cool plugin!

**Comment by wooningeire** [comment]
Yeah, customizing the different parameters would be good for tweaking things I couldn't/can't really settle in on myself, like balancing the distance between some keys and ability to hit the compound keys, etc., so people can experiment and optimize the layout to their liking. I have a couple ideas for how to organize the settings UI for those parameters after they've been added in.

SVG layouts would also be nice for supporting other systems (although there can also be the ability to edit the keymap of the default layout too) as well as for people who'd want to further optimize the layout beyond the default settings. Would likely need to decide on a format for the SVGs for designating the default keymap, key labels, etc.

Thank you ^^

**Comment by smunmun** [comment]
Consider using a similar format to the steno layout plugin that uses SVGs! I think there's two plugins but I'm not able to check right now.
________________________________

**Comment by wooningeire** [comment]
Currently I only know of Kaoffie’s SVG layout display plugin. Could use `data-` or namespace attributes to store the additional data, though it might be tedious having to manually add attributes to all the elements.

You can now trial some size settings by installing the current `sizesettings` branch of this repository as a plugin. (If you installed this repository from the command line last time, you might need to put `-e` before the URL and add `@sizesettings#egg=plover-touchscreen-stenotype` to the end of the git URL. Or you could just uninstall and then reinstall with `@sizesettings` at the end.) It's still in development, so essentially an alpha version that's incomplete and likely buggy. The settings section feels like a bit of a parameter dump at the moment too, which I'm still thinking through for now.

There's also an experimental branch `rotation-temp` which rotates the key groups, though it doesn't have all the size settings functionality merged into it as of yet (so it won't save/load the size settings either).

**Comment by wooningeire** [comment]
Still unoptimized and incomplete at the moment but the primary functionality has been added. Other features can be a separate thread
